# Generated by Django 5.1.3 on 2024-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('popularity_score', models.FloatField()),
                ('weight', models.FloatField()),
                ('yellow_image', models.URLField()),
                ('rose_image', models.URLField()),
                ('white_image', models.URLField()),
            ],
        ),
    ]
